contao:
  backend:
    badge_title: DEVELOPMENT
  image:
    sizes:
      topnews:
        width: 375
        height: 300
        resize_mode: crop
        densities: 2x, 3x
        css_class: max-w-full h-auto w-full block
        formats:
          jpg: [webp, jpg]
          webp: [webp, jpg]
          png: [webp, png]
        items:
          - media: "(min-width: 768px)"
            width: 800
            height: 600
            resize_mode: crop
            densities: 2x, 3x
          - media: "(min-width: 1200px)"
            width: 1920
            height: 1080
            resize_mode: crop
            densities: 2x, 3x
      news_image:
        width: 511
        height: 637
        resize_mode: crop
        css_class: aspect-news w-full
        formats:
          jpg: [webp, jpg]
          webp: [webp, jpg]
          png: [webp, png]
