app.tilastot.utils:
  resource: ../src/Utils
  type: annotation
app.tilastot.controller:
  controller: App\Controller\SeasonTicketController::order
  path: /seasonticket/order
  methods: POST
  schemes: [https]
