app.tilastot.utils:
  resource: ../src/Tilastot/Utils
  type: annotation
app.tilastot.aController:
  resource: ../src/Tilastot/Controller
  type: annotation
app.tilastot.controller:
  controller: App\Tilastot\Controller\SeasonTicketController::order
  path: /seasonticket/order
  methods: POST
  schemes: [https]
app.tilastot.seats_api:
  controller: App\Tilastot\Controller\SeatsApiController::getSeats
  path: /seasontickets/api/seats
  methods: GET
app.tilastot.postsController:
  controller: App\Tilastot\Controller\SocialMediaToolsUpload::upload
  path: /social-media-tools/posts/upload
  methods: POST
  schemes: [https]