on:
  push:
    branches:
      - "**"
      - "!main"
name: ğŸ‡¸ğŸ‡± Deploy steelers.de (Dev) ğŸ‡¸ğŸ‡±
jobs:
  web-deploy:
    name: ğŸ‡¸ğŸ‡± Deploy to Dev
    runs-on: ubuntu-latest
    steps:
      - name: ğŸšš Get latest code
        uses: actions/checkout@v4

      - name: ğŸ˜ Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.4"

      - name: ğŸš€ Deploy to dev
        uses: deployphp/action@v1
        with:
          private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          dep: deploy stage=dev
          deployer-version: "7.5.12"
